### ISSUE TITLE
[Feature Request] Add Get Key Feature and Static Key feature Support for TEE-IO validator 

### ISSUE THREAD

**Issue by kumars3-creator** [intel/tee-io-validator#156]
Hello,
I have 2 requests

1) As you all know Get Key feature is supported by newer CXL Devices 
Supporting CXL v 3.1. :: CXL_IDE_KM --> CXL_GETKEY Request

**Request**:: So for 1st part of request i have is, Add an option in .ini (Config file) to have an option for a End User to choose if we want to use Get Key from device. 

2) Now 2nd topic is regarding debug any Key setup errors in either side (Host/End point) or in-between logging/tooling side , using Dynamic keys make it very tough to debug or almost impossible to debug. 

**Request ::** Can we have an option in .ini (Config file) to have an option for End User to choose if we want to use a static Keys , which should be published in logs while setup, which static keys are used on which path RX/TX . This will make debugging allot easier . This actually applies to both PCIe and CXL.

Regards,
Sachin Kumar
(Sachin1.kumar@intel.com)

**Comment by mxu9** [comment]
A new command option "-k <key_type>" will be added to indicate how the key is generated.
There are below -k options:
- dynamic : Generate the key randomly in rootport side.
- fixed: Generate fixed keys in rootport side. The fixed key is like 0x1111..11
- cxl-get-key: Generate key in device side via IDEKM GET_KEY. If GET_KEY is not supported by device, it will fall back to dynamic key.

Default value is dynamic key.

**Comment by jyao1** [comment]
For 1, I agree to support in INI file.

For 2, it is debug only, I think it should be only for command line, not for INI file.

**Comment by kumars3-creator** [comment]
For 2nd request, agree with Jiewen feedback, as its for Debug purpose, having an option in command line should be sufficient.
