### ISSUE TITLE
PCIE-IDE KeyRefresh failed when testing on multi-card (>2)

### ISSUE THREAD

**Issue by mxu9** [intel/tee-io-validator#158]

**Comment by mxu9** [comment]
Please find below detailed steps for more information.

1.	4 cards are connected with x4x4x4x4 bifurcation.
2.	Configure IDE on the 1st card -> IDE configured successfully and the stream is secured.
3.	Configure IDE on the 2nd card -> IDE configured successfully and the stream is secured.
4.	Configure IDE on the 3rd card -> IDE configuration fails with an error message. “[error] pre_alloc_slot_ids failed because slot_id exceeds max rx/tx key_slots”
5.	Configure IDE on the 4th card -> IDE configuration fails with an error message. “[error] pre_alloc_slot_ids failed because slot_id exceeds max rx/tx key_slots”

ISSUE: Unable to configure IDE KeyRefresh on all the 4 cards.

Note:
1.	IDE and non IDE configuration and traffic works fine on all 4 cards. 
2.	Key refresh configuration and IDE traffic works fine on the 1st and 2nd card without any issues.

**Comment by jyao1** [comment]
I think we need to have rotation mechanism to support any number of cards.
