### ISSUE TITLE
GET_KEY feature test fails if bit[95:64] are random value

### ISSUE THREAD

**Issue by jyao1** [intel/tee-io-validator#160]
Intel Root Port SOC Hardware only supports programming lower 64bit IV counter value, and assumes bit[95:64] to be 0x80000000. That is a known limitation.

If the device can generate IV with bit[95:64] matching the default IV fixed field, that would be great. The new IV can be used for our RootPort SOC.

If the device generates IV with bit[95:64] being random value, then we are NOT able to use that initial IV value. And we have to use default IV and new generated KEY for KEY_PROG command.

To support the SOC compatibility, I think we needs to do some check for the bit[95:64] of the generated IV, then fall back to Default IV if it is not 0x80000000.

**Comment by mxu9** [comment]
> If the device generates IV with bit[95:64] being random value, then we are NOT able to use that initial IV value. And we have to use default IV and new generated KEY for KEY_PROG command.
> 
> To support the SOC compatibility, I think we needs to do some check for the bit[95:64] of the generated IV, then fall back to Default IV if it is not 0x80000000.

According to CXL Spec 3.1 Table 11-9, there are below 2 error conditions:
- Request to update Tx key, but the supplied key does not match the locally generated CXL.cachemem IDE key returned during the last CXL_GETKEY_ACK response.
- Request to update Tx IV, but the supplied IV does not match the Locally generated CXL.cachemem IV returned during the last CXL_GETKEY_ACK response.

I am not sure if we can fall back to Default IV after IDEKM GET_KEY.

**Comment by jyao1** [comment]
According to spec, if Default IV is used, supplied IV should be ignored.

We may test this as well.
