### ISSUE TITLE
Feature Request - To add support for specifying multiple root ports and endpoints in .ini file for setting up Link/Selective IDE Streams.

### ISSUE THREAD

**Issue by jshrivas** [intel/tee-io-validator#21]
For a Direct Attached Device topology, .ini file should support the capability to add multiple root ports and endpoint.

**For Example:**

[Ports]
rootport_1=02.0
rootport_2=04.0
rootport_3=06.0
rootport_4=08.0
endpoint_1=00.0
endpoint_2=00.0
endpoint_3=00.0
endpoint_4=00.0

This capability will help to setup multiple IDE Streams across multiple ports through one .ini file.

**Comment by mxu9** [comment]
Following below steps can setup multiple IDE Streams across multiple ports with one .ini file.

Does it solve your request?

1. Define rootport_x and endpoint_y in [Ports] section
```
[Ports]
rootport_1=02.0
rootport_2=04.0
rootport_3=06.0
rootport_4=08.0
endpoint_1=00.0
endpoint_2=00.0
endpoint_3=00.0
endpoint_4=00.0
```
2. Define Topology_x which describes how the rootport_x and endpoint_y are connected
```
[Topology_1]
type            = selective_ide   ; refer to IdeKmTestTopology.SelectiveIDE.md
connection      = direct          ; connect directly
bus             = 0x22
path1           = rootport_1,endpoint_1
stream_id       = 1

[Topology_2]
type            = selective_ide   ; refer to IdeKmTestTopology.SelectiveIDE.md
connection      = direct          ; connect directly
bus             = 0x22
path1           = rootport_1,endpoint_2
stream_id       = 2

[Topology_3]
type            = selective_ide   ; refer to IdeKmTestTopology.SelectiveIDE.md
connection      = direct          ; connect directly
bus             = 0x22
path1           = rootport_1,endpoint_3
stream_id       = 3

[Topology_4]
type            = selective_ide   ; refer to IdeKmTestTopology.SelectiveIDE.md
connection      = direct          ; connect directly
bus             = 0x22
path1           = rootport_1,endpoint_4
stream_id       = 4
```
3. Define Configuration_x which describes what configuration will be enabled
```
[Configuration_1]
type            = selective_ide ; refer to IdeKmTestConfiguration.SelectiveIDE.md
default         = 1             ; refer to IdeKmTestConfiguration.SelectiveIDE.md#no_special

[Configuration_2]
type            = selective_ide ; refer to IdeKmTestConfiguration.SelectiveIDE.md
pcrc            = 1             ; refer to IdeKmTestConfiguration.SelectiveIDE.md#no_special
```
4.  Then run below commands with combinations of Topology_x and Configuration_y like below.
     Note: below commands shall be run in different linux sessions.
```
./teeio_validator -f ide_test.ini -t 1 -c 1 -s Test.IdeStream
./teeio_validator -f ide_test.ini -t 2 -c 1 -s Test.IdeStream
./teeio_validator -f ide_test.ini -t 3 -c 1 -s Test.IdeStream
./teeio_validator -f ide_test.ini -t 4 -c 1 -s Test.IdeStream
```

**Comment by jshrivas** [comment]
Thank you Min.

**Comment by jshrivas** [comment]
Hi,

It appears specifying multiple ports and endpoints is throwing a parsing error.

./teeio_validator -f link_ide_x4x4x4x4.ini -t 1 -c 1 -s Test.IdeStream
[2024-04-17 11:39:32.084] teeio_validator version 0.1.0
[2024-04-17 11:39:32.084] ./teeio_validator -f link_ide_x4x4x4x4.ini -t 1 -c 1 -s Test.IdeStream 
[2024-04-17 11:39:32.084][error] Failed to parse test_suite.
[2024-04-17 11:39:32.084] Parse link_ide_x4x4x4x4.ini failed.

Configuration Setup:

[Main]
debug_level=info
pci_log=1

[Ports]
rootport_1=02.0    ; dev/func of rootport 1
rootport_2=04.0    ; dev/func of rootport 2
rootport_3=06.0
rootport_4=08.0
endpoint_1=00.0    ; dev/func of ssd1
endpoint_2=00.0
endpoint_3=00.0
endpoint_4=00.0

[Topology_1]
type            = link_ide   
connection      = direct          
bus             = 0xf5
path1           = rootport_1,endpoint_1
stream_id       = 1

[Topology_2]
type            = link_ide   
connection      = direct          
bus             = 0xf5
path1           = rootport_2,endpoint_2
stream_id       = 2

[Topology_3]
type            = link_ide   
connection      = direct          
bus             = 0xf5
path1           = rootport_3,endpoint_3
stream_id       = 3

[Topology_4]
type            = link_ide   
connection      = direct          
bus             = 0xf5
path1           = rootport_4,endpoint_4
stream_id       = 4

[Configuration_1]
type            = link_ide 
default         = 0
switch          = 0
partial_header_encryption = 0
pcrc            = 1
aggregation     = 0
selective_ide_configuration = 0
tee_limited_stream = 0

**Comment by mxu9** [comment]
> Hi,
> 
> It appears specifying multiple ports and endpoints is throwing a parsing error.
> 
> ./teeio_validator -f link_ide_x4x4x4x4.ini -t 1 -c 1 -s Test.IdeStream [2024-04-17 11:39:32.084] teeio_validator version 0.1.0 [2024-04-17 11:39:32.084] ./teeio_validator -f link_ide_x4x4x4x4.ini -t 1 -c 1 -s Test.IdeStream [2024-04-17 11:39:32.084][error] Failed to parse test_suite. [2024-04-17 11:39:32.084] Parse link_ide_x4x4x4x4.ini failed.
> 
Issue #43 is submitted to track this one.
