### ISSUE TITLE
Feature Request : SPDM flow log prints 

### ISSUE THREAD

**Issue by jshrivas** [intel/tee-io-validator#57]
Hi !

In the current TEE-IO Validator log - All SPDM traces info (CAPABILITIES, MEASUREMENT, CERTIFICATE....) are not visible.
It will help the end user to debugging if the log shows the info about the type of SPDM Msg.

Thanks

**Comment by mxu9** [comment]
Configure ide_test.ini like below to enable spdm log output. By default the spdm log is disabled.
```
[Main]
libspdm_log=1
```
