### ISSUE TITLE
Feature Request : Querying and Identifying version of tee-io validator

### ISSUE THREAD

**Issue by jshrivas** [intel/tee-io-validator#59]
Hi !

It would be great to be able to query the version of tee-io validator tool. This will help in understanding what version is currently installed on the system.

Thanks

**Comment by mxu9** [comment]
teeio-validator will release bi-weekly and update minor version then. 
Tester can check the version like below:
```
$ ./teeio_validator -h
[2024-05-16 02:15:51.811] teeio_validator version 0.1.0
```
